# install these frequently used R packages:

install.packages('tidyverse')
install.packages('BH')
install.packages('bookdown')
install.packages('data.table')
install.packages('doSNOW')
install.packages('foreach')
install.packages('ggrepel')
install.packages('gridExtra')
install.packages('gtable')
install.packages('haven')
install.packages('here')
install.packages('lexicon')
install.packages('magrittr')
install.packages('mailR')
install.packages('microbenchmark')
install.packages('ngramr')
install.packages('osfr')
install.packages('png')
install.packages('pracma')
install.packages('progress')
install.packages('readxlsb')
install.packages('rlecuyer')
install.packages('R.utils')
install.packages('Rcpp')
install.packages('RcppArmadillo')
install.packages('RcppGSL')
install.packages('RcppZiggurat')
install.packages('scales')
install.packages('snow')
install.packages('VGAM')
install.packages('xtable')
install.packages('wordcloud2')

